### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by kaiiam** [Southern-Cross-Plant-Science/cdno#1]
We'll need to choose and add an appropriate license.

**Comment by kaiiam** [comment]
ENVO for example uses `CC0 1.0 Universal` see their [LICENSE.txt](https://github.com/EnvironmentOntology/envo/blob/master/LICENSE.txt).

**Comment by kaiiam** [comment]
I'll leave this up to @CropStoreDb and @ramonawalls to decide what would be appropriate.

**Comment by kaiiam** [comment]
I've added `CC0 1.0 Universal` which mean anyone can use it for anything with no conditions. This is favored by OBO but if @CropStoreDb would prefer a different license let me know and I'll change it.

**Comment by CropStoreDb** [comment]
Yes, that seems in line with what we agreed on internally

Thanks
Graham
