### ISSUE TITLE
duplicate terms under different ids now under 'concentration of' 

### ISSUE THREAD

**Issue by ddooley** [Southern-Cross-Plant-Science/cdno#101]
e.g.

![image](https://user-images.githubusercontent.com/4000582/188010843-b643017d-7db9-47bd-8751-583b43783306.png)

the eqivalency statements are identical.  Would be great to have this resolved asap as its preventing foodon to reason without breaking the "no equivalent class axioms allowed" test.

To apply this same test to cdno would be something like:

robot reason --input cdno.owl --reasoner ELK --equivalent-classes-allowed none

**Comment by ddooley** [comment]
Could this be addressed soon!?

**Comment by LilyAndres** [comment]
Hi @ddooley, apologies. I will work on it straight away.

**Comment by LilyAndres** [comment]
@ddooley thanks for your patience. 

Regarding your comment: 
> Hmm, usually you deprecate terms native to your ontology, and put in the URI of the new term using "term replaced by" annotation. This provides a formal path for databases to upgrade their content. Is this possible at this point?

I followed the tutorial from [ODK on how to deprecate terms](https://ontology-development-kit.readthedocs.io/_/downloads/en/latest/pdf/)

Is looking something like this:


![Screen Shot 2022-09-12 at 4 56 34 pm](https://user-images.githubusercontent.com/25215773/189591577-d4d26286-46dd-47cf-84d3-dab985e6d3e2.png)

What do you think?

**Comment by ddooley** [comment]
Yes, that does it.  There is one other IAO "has obsolescence reason" annotation that would take the content you put in rdfs:comment, but the main thing is owl:deprecated, label gets preface "obsolete:" and IAO 0100001 term replaced by URI.

**Comment by LilyAndres** [comment]
Thanks @ddooley I will change the annotation to "has obsolescence reason" and then do the pull request, I will tag you when it's ready.

**Comment by LilyAndres** [comment]
@kaiiam I deprecated the terms using Protégé, directly into the cdno.owl file. So from now on every time I do a release I have to edit these terms right?

**Comment by ddooley** [comment]
Why would you need to edit the terms?  They can stay in the cdno.owl file.  Just remove their parent classes; its ok if they then float to top.  Protege has a menu item to hide deprecated classes by the way.  (I'll note that I did create a separate import file called deprecation_import.owl which I moved all deprecated terms into, and then attached as an import file to foodon.owl, but you don't have to do that.)

**Comment by LilyAndres** [comment]
@kaiiam OK, I will keep that in mind for the future, thanks.

**Comment by kaiiam** [comment]
I've added this label in case this comes back up so we can find it again easily.

**Comment by ddooley** [comment]
One other adjustment should be made:

'concentration of alditol in material entity'
'concentration of erythritol in material entity'
'concentration of glucitol in material entity'
'concentration of glycerol in material entity'
'concentration of isomalt in material entity'
'concentration of lactitol in material entity'
'concentration of maltitol in material entity'
'concentration of mannitol in material entity'
'concentration of xylitol in material entity'

All of these existing terms have the [obsolete concentration of polyol in material entity](http://purl.obolibrary.org/obo/CDNO_0200705) as a parent, so that needs to be disconnected.

**Comment by ddooley** [comment]
Your latest updates caused these to be duplicates again.  Perhaps move the deprecated terms out to a separate import file?  Or maybe you didn't do the deprecation in the cdno-edit.owl file?  The classes to be deprecated need to be moved to some template that isn't regenerated/written over.

**Comment by LilyAndres** [comment]
Thanks @ddooley I did the edits for this release in the cdno-edit.owl file and then I ran the release to create the final cdno.owl, but wha I can see is that they are still in the nutritional framework.csv template, I have the subclasses. 

Ontology ID | label | parent class
-- | -- | --
ID | AL rdfs:label@en | SC % SPLIT=\|
CHEBI:26191 | polyol | plant secondary metabolite
CHEBI:26191 | polyol | CHEBI:16646

Maybe this is where they should be removed as well?

Ontology ID | label | parent class
-- | -- | --
ID | AL rdfs:label@en | SC % SPLIT=\|
CHEBI:26191 | polyol | plant secondary metabolite
CHEBI:26191 | polyol |

**Comment by ddooley** [comment]
Yes, you either need to add the deprecation machinery right into that table: add columns there for the deprecated fields ("replaced by", owl:deprecated, mainly) so that robot picks them up. And then modify label to have "obsolete: ...", and delete all the other field content,
OR
remove them completely from that table, and keep the deprecated annotations & term in your main cdno-edit.owl file (or keep them in a separate deprecated_terms.owl file.)

d.

**Comment by LilyAndres** [comment]
Thanks @ddooley I'm on, I will let you know how it goes in a bit...

**Comment by LilyAndres** [comment]
@ddooley question, how can you see they are duplicated again? I ran 

robot reason --input cdno.owl --reasoner ELK --equivalent-classes-allowed none

before the release and I didn't see the duplicated terms, just so I can check after I make these edits again...

**Comment by ddooley** [comment]
Looks like duplicates are gone now, i.e. properly deprecated, thanks!  Just that they need to be declared so in your nutritional framework.csv table, or moved out of there into cdno-edit.owl , otherwise this will happen again?
