### ISSUE TITLE
xrefs are malformed - CURIEs should not have space after the colon

### ISSUE THREAD

**Issue by cmungall** [Southern-Cross-Plant-Science/cdno#108]
E.g

http://purl.obolibrary.org/obo/CDNO_0200174

`INFOODs: LA`

- the xref should be a CURIE (no space)
- INFOODs not registered with https://bioregistry.io/

**Comment by LilyAndres** [comment]
Apologies for the slow response, this issue has been fixed. Thanks a lot for reporting it @cmungall.
