### ISSUE TITLE
NTR: Dry matter

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#18]
## Preferred term label

Dry matter

## Textual definition

Difference between the total weight and the moisture content.

[doi.org/10.1046/j.0028-646X.2001.00320.x](https://nph.onlinelibrary.wiley.com/doi/abs/10.1046/j.0028-646X.2001.00320.x)

## Suggested parent term

Parent CDNO 'dietary nutritional component' 

We'll make it be subclass to 'plant matter' [ENVO:01001121]. With an axiom linking to 'dry' [PATO:0001824]

**Comment by LilyAndres** [comment]
Revising the definition @CropStoreDb suggested the following term from [URL ](https://dairy-cattle.extension.org/dry-matter-determination/#:~:text=Dry%20matter%20refers%20to%20material,DM%20portion%20of%20the%20feed.)

Material remaining after removal of water

**Comment by LilyAndres** [comment]
@kaiiam one question. The definition "dry matter" would be affected by the fact that we will make this term a subclass to 'plant matter' [ENVO:01001121], with an axiom linking to 'dry' [PATO:0001824]?

I think the definition: "Material remaining after removal of water", works.

**Comment by kaiiam** [comment]
If it's going to be subclass to 'plant matter' [ENVO:01001121], then mabye the def could be something like the following building on what you wrote:

> Material which remains after the removal of water from plant matter. 

Maybe also with exact synonym or have the label be: `dry plant matter`. Just because we want to be as specific as possible, but I understand that the community might already be used to saying "dry matter".

**Comment by LilyAndres** [comment]
> If it's going to be subclass to 'plant matter' [ENVO:01001121]

I think that's what was mention in the OBO request:

[ We'll make it be subclass to 'plant matter' [ENVO:01001121]. With an axiom linking to 'dry' [PATO:0001824]"](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1369#issuecomment-738468706)

I think we could use `dry plant matter`.

**Comment by kaiiam** [comment]
Cool sounds good! Its good to be as specific as possible in the label, we could have `dry matter` as a broad synonymy perhaps.

**Comment by LilyAndres** [comment]
> Cool sounds good! Its good to be as specific as possible in the label, we could have `dry matter` as a broad synonymy perhaps.

Ok, perfect. I will close this issue on Monday after confirmation with the team.

**Comment by LilyAndres** [comment]
Hey @kaiiam, after some discussion with @CropStoreDb we have decided to don't have a specific term, so the label would be 'dry matter' and the definition would be:

Material which remains after the removal of water 

We can probably add 'dry plant matter' as a synonym.

**Comment by kaiiam** [comment]
>  'dry matter'  def: Material which remains after the removal of water

@LilyAndres @CropStoreDb my issue with this is that it's super broad it literally refers to any dry matter, could be anything from dried tomatoes or dry space dust. A more general `dry matter` class would belong in ENVO or elsewhere then CDNO. I think what you guys mean is `dry plant matter`. I can understand that you'd prefer to use the label `dry matter` as that's what your users probably expect to see. I propose if you want to keep the label `dry matter` but it actually refers to only plant material then maybe keep the def:

> Material which remains after the removal of water from plant matter.

Let me know if I'm missing something here.

**Comment by LilyAndres** [comment]
Right, thanks @kaiiam.

So we will have the term "dry matter" with a specific definition:

Material which remains after the removal of water from plant matter.

We will add 'dry plant matter' as a synonym.

**Comment by LilyAndres** [comment]
We have decided to change the label for 'dry plant matter', in that way dry matter can be defined in other ontologies with a more general definition, we will use dry matter as a synonym.

**Comment by kaiiam** [comment]
Great it what I'd prefer to see as I think it's more correct. Remember we're moving from term glossary to an ontology so precision counts.

**Comment by LilyAndres** [comment]
Ok, thanks. I'm glad is better now. I copied the definition into the ROBOT template and added the synonym and changed the label, so I'm closing this issue now.
