### ISSUE TITLE
NTR: soluble dietary fibre

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#22]
For new term requests, please provide the following information:

## Preferred term label

soluble dietary fibre

## Textual definition

Water- soluble/well fermented fibres

[Anita, FP. 1973.](https://www.cabdirect.org/cabdirect/search/?q=au%3a%22Antia%2c+F.+P.%22)

## Suggested parent term

dietary fibre

**Comment by LilyAndres** [comment]
A definition from [wikipedia](https://en.wikipedia.org/wiki/Dietary_fiber): 

Dietary fiber which dissolves in water – is generally fermented in the colon into gases and physiologically active by-products, such as short-chain fatty acids produced in the colon by gut bacteria.

**Comment by LilyAndres** [comment]
According to Huhtanen, P., 2006.
Digestion of both soluble and insoluble fibre is solely dependent on microbial fermentation, no digestion will take
place in the small intestine; however fibre that escapes rumen digestion may be degraded in the hind-gut.

The description above suggests that the digestion of fibre is mainly in the rumen and only some other fibre is degraded in the hind-gut, which is different in monogastric animals.

**Comment by LilyAndres** [comment]
I propose the following definition:

A dietary fibre which dissolves in water generally fermented in the colon, primarily by gut bacteria in monogastric animals. 

Two references were used:
[Negasu, G. 2017.](https://www.arcjournals.org/pdfs/ijrsas/v3-i10/4.pdf)
[Richards et al., 2005.](https://cdnsciencepub.com/doi/pdf/10.4141/A05-049)

**Comment by LilyAndres** [comment]
It might be better to remove "A":

Dietary fibre which dissolves in water generally fermented in the colon, primarily by gut bacteria in monogastric animals.

**Comment by LilyAndres** [comment]
Just adding "and is" words from @CropStoreDb.

Dietary fibre which dissolves in water and is generally fermented in the colon, primarily by gut bacteria in monogastric animals

**Comment by CropStoreDb** [comment]
Is your form Aristolotean ?


Soluble dietary fibre is a carbohydrate fibre that is water soluble and is generally able to be fermented in the colon, primarily by gut bacteria in monogastric animals

Insoluble dietary fiber includes carbohydrate or pectin fibres that are insoluble in water……

to dissolve in water – how does this differ from  ‘is water soluble’ ?

**Comment by LilyAndres** [comment]
Suggested by @CropStoreDb:

Dietary fibre which dissolves in water and is primarily fermented in the colon of monogastric animals by gut bacteria
