### ISSUE TITLE
Add details to README.md

### ISSUE THREAD

**Issue by kaiiam** [Southern-Cross-Plant-Science/cdno#3]
Hey @LilyAndres, we'll need to add some descriptive information to our [README.md](https://github.com/Southern-Cross-Plant-Science/cdno/blob/master/README.md). Definitely the title: `Crop Dietary Nutrition Ontology`, and any other supporting/descriptive information about the project. See [ENVO's](https://github.com/EnvironmentOntology/envo/blob/master/README.md), or @ramonawalls [BCO](https://github.com/BiodiversityOntologies/bco) or [PCO](https://github.com/PopulationAndCommunityOntology/pco) `README.md` files as examples.

**Comment by kaiiam** [comment]
@LilyAndres let me know when you have this info prepared (no rush) and I can teach you how to use a modified version of the [GO daily workflow](https://go-ontology.readthedocs.io/en/latest/DailyWorkflow.html) so that you can do it via a branch and pull request. We don't have to do things that way but it's highly recommended as a better practice.

**Comment by LilyAndres** [comment]
Hi @kaiiam thanks for this, yesterday I wanted to incorporate that information but I thought could be better to do it on the branch which I forgot how to do it, I have done it before, last year I think but if you can help me, would be great. I think I can have everything ready at the end of the day, but let me know which day would be better for you.

**Comment by LilyAndres** [comment]
@maumauleon sorry I didn't include you earlier, we will add more info ASAP.

**Comment by kaiiam** [comment]
@LilyAndres I've written a similar [envo-editors-daily-work-flow](https://github.com/EnvironmentOntology/envo/wiki/Adding-classes-to-ENVO#envo-editors-daily-work-flow) protocol for ENVO. You can basically just sub out ENVO for CDNO in that protocol.

The main ideas is to do things in a branch instead of on the main development branch:  you do with with a command like: `git checkout -b issue-x` where `x` corresponds to an issue on the tracker. Then when you push to that branch and go to the github page it'll let you create a pull request. 

I've been wanting someone to give my directions a try. It'd be great if you wouldn't mind trying it based on those instructions (with CNDNO instead of ENVO) and let me know how it goes, if anything was unclear etc. 

You could do it with just changes you want to add to the make file and you can use this issue #3 to make a branch with. 

Thanks!

**Comment by LilyAndres** [comment]
Hey @kaiiam sounds good, I will try the protocol and let you know how it goes. Thanks for the help!

**Comment by kaiiam** [comment]
We don't HAVE to do things this way but it's highly recommended as a best/better practice, (based on the GO experience). So if we build good habits now we'll be better off in the long run, especially if this project lasts a while.

**Comment by LilyAndres** [comment]
No worries, I definitely need to boost my "skills" on the command line.

**Comment by kaiiam** [comment]
The alternative being to directly make commits to master without creating a branch and a pull request, the danger in that is if multiple editors are doing it it can more easily lead to merge conflicts, whereas when we use branches/pull requests we can check and fix merge conflicts more easily. The other issue we've run into in ENVO is spurious diff files when people don't use the latest version of Protege. So once you start making edits to the ontology itself make sure you're using the latest version of Protege.

**Comment by kaiiam** [comment]
@LilyAndres I noticed there's a funky non displaying character in the readme.md can you fix it?

<img width="258" alt="image" src="https://user-images.githubusercontent.com/12255688/103363290-bd7c9c00-4a88-11eb-9cb0-fad2b8ca7dc7.png">

**Comment by LilyAndres** [comment]
Hey thanks @kaiiam, I actually changed the README to incorporate the Scope of the CDNO and I did it through the a branch following the steps in [https://github.com/EnvironmentOntology/envo/wiki/Adding-classes-to-ENVO#envo-editors-daily-work-flow](url), let me know if it's ok please

**Comment by kaiiam** [comment]
@LilyAndres the above link doesn't lead anywhere, I was just saying to get rid of that non displaying character in the file https://github.com/Southern-Cross-Plant-Science/cdno/blob/master/README.md.

**Comment by kaiiam** [comment]
Oh I see the link is just not displaying on wiki when you click but its to the page I wrote, yes try to do it that way. Currently it's not showing up as a pull request once you run `git push` it'll show up on the github repo as a pull request.

**Comment by LilyAndres** [comment]
Hi Kai,

Regarding to this issue, I followed the steps from ENVO-daily-workflow<https://github.com/EnvironmentOntology/envo/wiki/Adding-classes-to-ENVO#envo-editors-daily-work-flow>, in order to update the README with the scope, the last command was "git push origin issue-3":

[cid:2f00d3bb-10c8-4c7c-8076-29bc3bd81766]

The next step is:

  1.  On envo pull requests page<https://github.com/environmentontology/envo/pulls>:

click on Compare and Create Pull Request

but I can't see my request. Not sure if there is some steps missing...
Thanks.


Regards,

Lili


Liliana Andres | PhD candidate
Southern Cross Plant Science| Southern Cross University | PO Box 157 | LISMORE  NSW  2480, AUSTRALIA
T: +61 416844027| E: l.andres.hernandez.18@student.scu.edu.au<mailto:l.andres.hernandez.18@student.scu.edu.au> W: http://www.scu.edu.au/scps/


[1506039948851_SCPS.jpg]
________________________________

**Comment by kaiiam** [comment]
@LilyAndres are you trying to make a PR to ENVO or to CDNO? Remember that the https://github.com/EnvironmentOntology/envo/wiki/Adding-classes-to-ENVO#envo-editors-daily-work-flow protocol is configured to add to ENVO, so if you're using it for CDNO you'll have to modify it slightly. Make sure the issue corresponds etc, and check the CDNO page, although I don't see any PRs there. Maybe you can sent some screen shots of what happens when your run `git status`

**Comment by kaiiam** [comment]
@LilyAndres it looks like you took care of this in https://github.com/Southern-Cross-Plant-Science/cdno/commit/bfdca688d8b83a9f9bc7879ec2db977fe01ea956 ? if so and or if you're happy with the README then go ahead and close this.

**Comment by kaiiam** [comment]
Although maybe not because this section is not accurate since were not just using the edit file. We should maybe update this. @LilyAndres You'll have to explain it for your thesis anyway so you can just add some of what you wrote to the readme. 

```
Editors' version

Editors of this ontology should use the edit version, src/ontology/cdno-edit.owl
```

**Comment by LilyAndres** [comment]
Thanks @kaiiam, I used a template to describe the README, so some of the information there is not accurate. I will update this once I have the first release...

**Comment by kaiiam** [comment]
Sounds good!

**Comment by kaiiam** [comment]
@LilyAndres did you took care of this? I though you had if so this is good to close.

**Comment by LilyAndres** [comment]
Complete it with the new changes for Compositional DNO.
