### ISSUE TITLE
INFOOD & USDA Mapping annotation property

### ISSUE THREAD

**Issue by kaiiam** [Southern-Cross-Plant-Science/cdno#32]
@LilyAndres @CropStoreDb @ddooley @ramonawalls

Regarding the CDNO mappings, I realize it might not quite show up how you’d want/expect. In the robot template it makes sense as USDA and INFOODS are in the column headers.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/12255688/106475184-a9ef9700-6473-11eb-995d-74cbd432466a.png">

However, those won’t get compiled so what will end up happening is we’ll get 

<img width="409" alt="image" src="https://user-images.githubusercontent.com/12255688/106475225-b5db5900-6473-11eb-963b-001da78752a8.png">

Perhaps this is desired and we can stop there, however, if not I propose two possible solutions:

1) Change the annotation property from `http://www.geneontology.org/formats/oboInOwl#hasDbXref` to a newly invented one in CDNO perhaps something like `http://www.geneontology.org/formats/oboInOwl#USDADbXref` 

2) Add something like `USDA_` to the beginning of all the rows in the mappings csv and keep the `hasDbXref` annotation property. 

<img width="922" alt="image" src="https://user-images.githubusercontent.com/12255688/106475897-76f9d300-6474-11eb-9420-291406acb7f0.png">

That way it'll show up looking something like this:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/12255688/106476174-c50ed680-6474-11eb-8e4a-e0f76d23b0b2.png">

I'd advocate for solution `2` but would like to hear everyone's thoughts/ suggestions.

**Comment by ddooley** [comment]
Definitely #2 in my book. I'd use a colon separator, paving the way for such a string to be "ontologized/URI'd" if the provider ever got around to it. So INFOODS:ASH   , and  USDA_NDB:1007  (originates in https://data.nal.usda.gov/dataset/usda-national-nutrient-database-standard-reference-legacy-release)

d.

**Comment by kaiiam** [comment]
Great thanks @ddooley and @ramonawalls. @CropStoreDb and @LilyAndres let us know if you agree. 

If so @LilyAndres can you go ahead and update the mappings.csv file (google drive is ok for now) then re-download it with the updates?

**Comment by LilyAndres** [comment]
Thanks, @kaiiam and @ddooley I made the changes and they are now in the pull request.

**Comment by kaiiam** [comment]
@LilyAndres see my comments in https://github.com/Southern-Cross-Plant-Science/cdno/pull/33 once you fix that were good to go!
