### ISSUE TITLE
Fix grammer in definitions of concentration terms

### ISSUE THREAD

**Issue by kaiiam** [Southern-Cross-Plant-Science/cdno#35]
Note about the definitions in the concentration terms, the grammer is a little off it's

<img width="407" alt="image" src="https://user-images.githubusercontent.com/12255688/106675756-b105ca80-6583-11eb-824f-9b8c6783aee6.png">

The concentration of X when measured in plant structure. 

It should be something like `a plant structure.` or `some plant structure.` @CropStoreDb and @LilyAndres any preferences? I think some works. I'll add this to the DOSDP file before we run all the new terms. 

@LilyAndres what's the plan are you going to run the whole workflow soon? If so I we should quickly address this.

**Comment by LilyAndres** [comment]
Thanks @kaiiam I think some is ok and yes I'm planning to run the whole workflow soon.
