### ISSUE TITLE
Approval of CDNO in OBO foundry

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#44]
Here is the [link](http://www.obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) with steps to integrate CDNO in OBO repository 
We need to follow Step 3. Approval

**Comment by LilyAndres** [comment]
@kaiiam Just for future references

**Comment by kaiiam** [comment]
from james here https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1369#issuecomment-775133180 ref https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1425

**Comment by LilyAndres** [comment]
Thanks @kaiiam. I think I fix everything, we will see if it's all good now.
