### ISSUE TITLE
I need some excel files related to the development of the CDNO for my thesis 

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#48]
I need the CDN-DF v2.0 and the lookup table excel files to describe them in my thesis as supplementary data, therefore I would like to add them in the "utility" folder.

**Comment by kaiiam** [comment]
Sounds reasonable since that's where we put the conversion scripts to go from the original NCF to the template inputs.

**Comment by LilyAndres** [comment]
Files were updated, I'm closing this issue.
