### ISSUE TITLE
concentration of 5-formyltetrahydrofolic acid in plant structure

### ISSUE THREAD

**Issue by ddooley** [Southern-Cross-Plant-Science/cdno#49]
This concentration points to CHEBI:15640 - 5-formyltetrahydrofolic acid, but it seems like the hasDbXrefs are coming in at too broad a level. Can the INFOODs and USDA_NDB tags be associated with concentrations at a more granular level? Is it really the case that multiple ones are correct for 5-formyltetrahydrofolic acid? Ideally INFOODs and USDA_NDB are only 1-1 DB Xrefs.

![image](https://user-images.githubusercontent.com/4000582/110212931-8e045a00-7e52-11eb-9514-6030d251ee8e.png)

**Comment by LilyAndres** [comment]
Hi @ddooley, I'm so sorry for my delayed reply I didn't get a notification, I will check what's wrong.

Thanks for finding this it's an error, it should have been associated only to USDA_NDB: 1192 and not to all the other cross-references, I will check what was wrong and create an update at the end of this month.

**Comment by LilyAndres** [comment]
@ddooley I have some questions about this issue but before that, I just wanted to let you know that the new release will have the changes for this mistake, now 5-formyltetrahydrofolic acid is only associated to USDA_NDB: 1192.

For the granular level of tagnames from USDA/INFOODs, I associated the term 'concentration of carbohydrate' to the following code numbers from USDA: 
1005	Carbohydrate, by difference
1050	Carbohydrate, by summation
1072	Carbohydrate, other

Do you think it would be better to only associate it to "1072" "carbohydrate, other"?

**Comment by LilyAndres** [comment]
@ddooley what's your opinion about it? If you think is ok I will close this issue. Otherwise we can ask people from INFOODs and USDA?

**Comment by ddooley** [comment]
So the 'concentration of carbohydrate' would be a generic ontology class that wouldn't commit to how that concentration was analyzed. Under it we'd place subclasses for 1005, 1050, and their 1072 ("Carbohydrate, other" which in their semantic translates to "neither by difference or summation").  'concentration of carbohydrate' wouldn't technically map to any USDA codes directly.  A question is whether USDA wants to add a generic 'concentration of carbohydrate' code to their flat list to indicate unspecified analytic method, but that probably wouldn't be used by them, so rather useless on their side.

**Comment by LilyAndres** [comment]
@Graham-J-King What do you think? I think this might be something related to the Analytical methods class?

**Comment by Graham-J-King** [comment]
@LilyAndres @ddooley 
My thoughts: I think we have to be careful in the tagging process where they may be one-to-many or many-to-one relationships inherent. I would think most people see a tag associated and assume a one-to-one relationship. There is a need for some association of _evidence_ trail or relationship to be declared, as xrefs can get very messy to manage and lead AI astray.
