### ISSUE TITLE
Some confusion in FoodOn regarding CHEBI vitamins

### ISSUE THREAD

**Issue by ddooley** [Southern-Cross-Plant-Science/cdno#50]
I am in the process of deprecating FoodOn nutrient terms in favour of the CDNO ones. On the vitamin branch I've managed to eliminate FoodOn duplicates for the most part, but there are some vitamin B & C underlings that I'm not sure about.  See the bolded FoodOn vitamin branch (which uses NCIT Vitamin term http://purl.obolibrary.org/obo/NCIT_C944) which will be obsoleted soon: 

![image](https://user-images.githubusercontent.com/4000582/111265472-5fbb1300-85e6-11eb-8220-d4f01b8baa1d.png)

I wasn't sure if the underlings given on the FoodOn side should be added to the CHEBI side? Or are they erroneous?

**Comment by LCCarmody** [comment]
Hi Damien, I thought this might be the same [issue in MAXO](https://github.com/monarch-initiative/MAxO/issues/224) , but it just seems related.  @matentzn May be able to help make a more permanent solution.

**Comment by LilyAndres** [comment]
Thanks @ddooley this is an issue that involves a discussion with CHEBI curators. As far as I know, CHEBI is managing vitamin as a role and so these might be added at some point to CHIRO? This is one of the issues I have when I was trying to describe the vitamins, they are roles but they are also nutritional components. I think I will put everything together in a document so it's easier to check what we need from the roles that are described in CHEBI.

**Comment by LilyAndres** [comment]
I think we can also close this issue, right @ddooley ?
