### ISSUE TITLE
Mapping mismatch. 

### ISSUE THREAD

**Issue by kaiiam** [Southern-Cross-Plant-Science/cdno#54]
@LilyAndres noticed the following terms are miss-matched between the `modules/mappings.owl` and `modules/chemical_concentration.owl` files. 

```
CDNO:0200181	5-formyltetrahydrofolic acid
CDNO:0200182	vitamin B
```
It should be an easy fix to just switch them in the `templates/mappings.csv` to be in the same order as they are in the `templates/chemical_concentration.csv` file. 

Maybe @LilyAndres can double check to see if there are any others that got switched. I suspect this happened because there was some confusion about the vit b term, but so maybe its the only one but if were not sure it's good to check.

**Comment by kaiiam** [comment]
@LilyAndres did this get sorted? If so go ahead and close it.

**Comment by LilyAndres** [comment]
@kaiiam I will close this issue now, as the changes have been merged into the master branch.
