### ISSUE TITLE
CDNO dietary role class

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#65]
## Preferred term label

dietary role

## Textual definition

A biological role that may be assigned to a dietary nutritional component based on evidence that supports a function defined at the levels of molecular interaction, cellular process or physiological role.

## Suggested parent term

'role' [BFO:0000023] 

## Attribution
https://orcid.org/0000-0002-5975-6051

**Comment by LilyAndres** [comment]
The 'dietary role' class will describe interactions of food components with human physiological function, where a dietary nutritional component may be associated with one or more roles. 

@ddooley, @ramonawalls, @kaiiam Please let us know what you think.

We (@CropStoreDb and I) have a framework in progress, please have look at [CDNO_Dietary_role_class_V2.xlsx](https://github.com/Southern-Cross-Plant-Science/cdno/blob/master/src/ontology/util/CDNO_Dietary_role_class_V2.xlsx)

**Comment by kaiiam** [comment]
So far so good @LilyAndres! If we want to have a role hierarchy that's a good label for it. I can't really comment on the language in this definition it's well written but I don't know if that's what we mean or not. I'd say we go for it for now so we can have a top level for our vitamin role classes imported from CHEBI.

**Comment by ddooley** [comment]
We should raise the definition in the IFOW group - maybe an email.  One thing to anticipate is dietary role of food with respect to animal nutrition.  Lots of research re. domesticated animals and optimal diets. So possibly a general 'dietary role' and then a 'human dietary role' if as you mention 'human physiological role' is key.  Also, can nutrient related molecular interaction and cellular process subsumed under physiological role?

**Comment by kaiiam** [comment]
Getting more opinions is good, but trying right now to represent everything might be a bit much to handle. Clarifying scope human or animals is good but I don't think we'd want to go too much further on that right now. 

> Also, can nutrient related molecular interaction and cellular process subsumed under physiological role?

I fee like this is a whole other can of worms  which I bet isn't currently in scope for @LilyAndres.

**Comment by LilyAndres** [comment]
Thanks @kaiiam, yes I agree that we definitely don't want to represent all but being part of the IFOW meetings and some other people confused about the vitamins and energy terms, I thought it would be good to state what's the big picture of CDNO and future classes. What I have see from the [KnowFOOD](https://www.youtube.com/channel/UCkzkKCDLvX01LZ-uGre5XhQ) meetings, IFOW meetings and from some other collaborators and contacts, I think there might be some in-progress work at the moment, but the ontologies I have seen are not following the OBO principles. For this reason, I thought it would be good if we discuss the issues here so we can see if this or other classes that will be part of the CDNO see #66 and #67 are something that is in progress by other groups?

With this I would say, thanks@ddooley, yes let's share this with the IFOW. 

>So possibly a general 'dietary role' and then a 'human dietary role' if as you mention 'human physiological role' is key

I think we can start with 'human dietary role' at the moment and see how it goes?

**Comment by ddooley** [comment]
Yes, "human dietary role' is good!

**Comment by CropStoreDb** [comment]
Agreed.

**Comment by LilyAndres** [comment]
A new draft with terms for this class can be found in the following[ link](https://docs.google.com/spreadsheets/d/1wyP2vqzJyC0Tba0yzS_IJXG6wpVuIVQH/edit#gid=958732661), feedback anyone?

**Comment by LilyAndres** [comment]
@maweber-bia Also just as a quick update seeing that you are bringing 'nutrient role' into the discussion in issue #30, @Graham-J-King, and I have been working on a draft framework for the new potential classes in CDNO, please also have a look at issues #66 'nutritional functional attribute' and #67 'physical attribute' so you can see the proposed definitions. 

We are planning to send it to the IFOW group and contact the people from ONS to see how can we collaborate, @mateolan I think you have seen the previous version before, open to feedback.

**Comment by maweber-bia** [comment]
Great! Thank you for the follow-up
I will have a look and will be pleased to discuss it with the IFOW group
cheers,
Magalie

**Comment by LilyAndres** [comment]
This class has been added in the release 3.0, I will close this issue now.
