### ISSUE TITLE
CDNO nutritional functional attribute class

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#66]
## Preferred term label

nutritional functional attribute

## Textual definition

A functional attribute that inheres in one or more dietary nutritional component (or food material) and may contribute to a dietary role.

## Suggested parent term

'specifically dependent continuant' [BFO:0000020]

## Attribution

https://orcid.org/0000-0002-5975-6051

**Comment by CropStoreDb** [comment]
This is one of the proposed classes where 'functional attribute' is initially suggested as _sensu_ http://purl.obolibrary.org/obo/TXPO_0000825 (A physical attribute inhering in a bearer by virtue of the bearer's function) and is distinct from the proposed 'dietary role' class. The distinction is that the physical attribute would expect to exist independent of whether used in diet or not. However, this may need to be extended beyond physical if is to include chemical attributes such as 'anti-oxidant' or 'chelator'.

 'food material' is _sensu_ http://purl.obolibrary.org/obo/FOODON_00002403 and of course 'dietary nutritional component' refers to http://purl.obolibrary.org/obo/CDNO_0000001.

**Comment by LilyAndres** [comment]
A new draft with terms for this class can be found in the following [link ](https://docs.google.com/spreadsheets/d/1wyP2vqzJyC0Tba0yzS_IJXG6wpVuIVQH/edit#gid=958732661), feedback anyone?

**Comment by LilyAndres** [comment]
This class has been added into CDNO in the 3.0 release. I will close this issue now.
