### ISSUE TITLE
NTR: Salt soluble protein

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#7]
We are going to create some nutritional framework terms in CDNO the term is "Salt soluble protein" which does not exist in any other OBO ontology as far as I am aware

## Preferred term label

Salt soluble protein

## Textual definition

Based on Razlin's definition from Nutrition schema_framework_002:

> A family of globular proteins that have higher molecular weights than albumin, and makeup the majority of legume seed storage protein. Examples of globulin: legumin and vicillin (soybean). These proteins can cause allergic reactions if they bind with human IgE antibodies.

## Suggested parent term

[CHEBI:36080 - protein](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=36080)

**Comment by LilyAndres** [comment]
This term is no longer required as a "dietary nutritional component" in the CDNO, instead, it was considered an extraction method.

**Comment by kaiiam** [comment]
Dido my comment in #8. I take it we won't have an immediate need for this term.
