### ISSUE TITLE
Definition of labels and reuse of CHEBI terms in the CDNO mineral nutrient class

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#70]
This issue has been created to discuss the labels and reuse of CHEBI terms in the CDNO mineral nutrient class.

Having checked some CHEBI labels that were incorrectly re-labeled in CDNO (see issue #64), e.g. re-labeled as `'calcium'`, we identified some terms where the representation of mineral nutrients could be improved in the dietary nutrition domain:

**1.** We propose the reuse of other CHEBI terms. For example the ionic form (atom with more or less electrons) of an element is often measured when quantifying e.g. the ['concentration of calcium' in milk](https://www.canterbury.ac.nz/media/documents/science-outreach/calcium.pdf), typically using a method (eg ICP-MS) that estimates the concentration of calcium (2+) ions. However, the quantity being calculated is typically expressed as atomic Ca, even though it may be present in multiple bound, ionised or other molecular forms (eg salts). In some situations, there may be an assay that allows the estimation of concentration (via stoichiometry) of a specific salt.

Thus, within the `'dietary nutritional component'` and `'dietary nutritional component concentration'` classes, we would include eg. `'calcium(2+)'` [CHEBI:29108] in addition to `'calcium atom'` [CHEBI:22984].

**2.** To ensure there is vocabulary more tailored to dietary nutrition, we propose the adoption of the terms `‘dietary calcium’`, `‘dietary magnesium’` etc, and under these have options for hierarchical sets of terms including: `‘calcium atom’`, `‘calcium ion’`, `‘calcium salt’`.  

We welcome feedback to know whether this provides a way forward to help nutritionists navigate to appropriate ChEBI terms and distinguish in what form an element may be present, quantified/estimated or reported depending on assay.

**3.** The hierarchical classification would look something like this, using `'calcium'` as an example: 
![image](https://user-images.githubusercontent.com/25215773/125621432-d9104dac-5504-4a23-973e-88a557299ee1.png)

**Comment by LilyAndres** [comment]
@ddooley, @CropStoreDb, @kaiiam, @laurenechan, @LuciaSegovia, @maweber-bia, @mateolan, what do you think?

**Comment by ddooley** [comment]
Looks good to me - your classes like "dietary calcium" reflect the amount of information available from existing datasets. The subclasses can be referenced if more specific calcium form testing data is available.

**Comment by maweber-bia** [comment]
I fully agree with the proposals, well done!

**Comment by LuciaSegovia** [comment]
Brilliant!! I really like it :) Just one suggestion, for iron, you may want to include haem and non-haem into the hierachy.

**Comment by LilyAndres** [comment]
Great thank you all :) @LuciaSegovia thanks, I will take that into account, I might need your help to check the hierarchical classification at some point, we will be in touch.

**Comment by LuciaSegovia** [comment]
Sure! No problem :)

**Comment by LilyAndres** [comment]
Hello, we have completed a framework proposal for the `'mineral nutrients'`, please follow the [link](https://docs.google.com/spreadsheets/d/1o7uqQGyorG1JekzqJe1glJg83jP_P_KD/edit#gid=503376986) and feel free to make any comments in column "N", your feedback is much appreciate it :) 
@maweber-bia, @LuciaSegovia, @ddooley

**Comment by kaiiam** [comment]
Looks good @LilyAndres (from a quick glance I didn't study it all in depth). I'd make sure to add a column of the CHEBI iri's or CURIE's so this can get turned into a robot template.

**Comment by maweber-bia** [comment]
Nice job! just wondering why you did not include "dietary" in the label of silicon dioxide

What will you do with the scientific publications referenced in the spreadsheet? Actually, it is good to know such references

**Comment by kaiiam** [comment]
We can (and I think should) add the publication links as cross-references to the terms.

**Comment by laurenechan** [comment]
My apologies if we have already discussed this, but I am slightly concerned with categories like 'dietary lead' or 'dietary arsenic' being subclasses of 'mineral nutrient' given that lead and arsenic are not nutrients. Similar concerns arise for any elements that may be consumed in the diet but do not have actual 'nutrient' capacities for humans. Do we have options for ways to include these dietary components with a different parent class?

**Comment by kaiiam** [comment]
Good points @laurenechan. We should be really clear about what is meant by `mineral` and  `nutrient` and based on is definition make sure we don't subsume anything under it that should be. 

Like Lauren suggests we should have a different parent, something high-level and perhaps from CHEBI for chemicals that we import from CHEBE and present but don't want to call 'nutrients'

**Comment by maweber-bia** [comment]
As previously discussed (see issues #65,  #30)  a "dietary component" can have either a "nutritional" or a "non-nutritional" role

This should be clear in the hierarchy of components as well :

"dietary"  indicates that the component is provided by food (in a diet)  but we should have dietary nutritional components and dietary non-nutritional components (those components which have a biological role - either positive effect or negative effect- but which are not nutrients)

**Comment by LilyAndres** [comment]
Thanks for your comment @laurenechan. We have discussed this matter and we think maybe replacing the label of the `'dietary nutritional component'` class with `'dietary chemical component'` could work? As @maweber-bia mentioned, we need to think about how to define chemical components that are not necessary nutrients but are still in the diet. We presented a Venn diagram of these categories in one of the IFOW monthly meetings in Sept 2021.

![image](https://user-images.githubusercontent.com/25215773/150881275-ba130474-61bd-48e9-9d44-dfecc5e2c51b.png)
In this case, the minerals that are ingested in the diet but that are not nutrients could be classified in a separate subclass, for example ‘mineral non-nutrient’.  I’m not sure whether we yet have the ideal label but this is the idea. Here is an example of the hierarchical classifications:

![image](https://user-images.githubusercontent.com/25215773/150881453-fe44e6bd-b12b-4d2c-a385-29e866f13079.png)

What do you think?

**Comment by LilyAndres** [comment]
This issue has been solved in the 3.1 release. I will close it now.
