### ISSUE TITLE
NTR: Water soluble protein

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#8]
We are going to create some nutritional framework terms in CDNO the term is "Water soluble protein" which does not exist in any other OBO ontology as far as I am aware

## Preferred term label

Water soluble protein

## Textual definition

Based on Razlin's definition from Nutrition schema_framework_002:

> Major category of storage proteins that are soluble in proteins.

## Suggested parent term

[CHEBI:36080 - protein](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=36080)

**Comment by LilyAndres** [comment]
This term is no longer required as a "dietary nutritional component" in the CDNO, instead, it was considered an extraction method.

**Comment by kaiiam** [comment]
Ok cool, I take it it's not longer in the Nutritional Framework Term hierarchy? Will the cropDB need this as an annotation term? If not then I'd say close this issue.

**Comment by LilyAndres** [comment]
Thanks @kaiiam 

>  it's not longer in the Nutritional Framework Term hierarchy? 

No, "water soluble protein" it's no longer on it so will close the issue now.
