### ISSUE TITLE
CHEBI annotations are not being imported into CDNO

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#92]
I realise that the new imported terms from CHEBI are not being imported into CDNO: 

Below is an example of `'chitosan' [CHEBI:16261]` from the CDNO-edit.owl file in Protege:

<img width="1234" alt="Screen Shot 2022-06-21 at 2 12 42 pm" src="https://user-images.githubusercontent.com/25215773/174714944-da82bdc1-3ca3-49b3-aa52-13a85553ad3d.png">

Just for clarity, this and all the rest of new carbohydrate terms have been added into the imports/`cheri_terms.txt` and include/`NCF_includes.txt` files. 

But I can't figure out why the annotations from CHEBI are not in the CDNO-edit.owl file.

**Comment by LilyAndres** [comment]
I ran the workflow again after solving an issue with the memory [issue-623](https://github.com/INCATools/ontology-development-kit/issues/623), this solved the issue of the imports and now I can see the annotations :)

<img width="1064" alt="Screen Shot 2022-06-22 at 7 44 21 pm" src="https://user-images.githubusercontent.com/25215773/174998620-8e36cd24-d8b8-4eee-b5c6-304446e46d05.png">

So we are ready to to do the next release, I will close the issue now.

**Comment by kaiiam** [comment]
Great! Glad that Nico was able to help you figure it out.
