### ISSUE TITLE
Error in the design pattern during the release

### ISSUE THREAD

**Issue by LilyAndres** [Southern-Cross-Plant-Science/cdno#97]
I'm trying to run the make file, the command is:

`./run.sh make all_modules`

And I get the following error:

```
dosdp-tools generate --table-format=csv --template=patterns/chemical_concentration.yaml --outfile=modules/chemical_concentration.tmp.owl --obo-prefixes=true --infile=templates/chemical_concentration.csv
make: dosdp-tools: Permission denied
make: *** [Makefile:114: modules/chemical_concentration.owl] Error 127
```

**Comment by kaiiam** [comment]
This is probably a docker issue as I am able to run it on my computer. Perhaps something we should ask Nico for help with.

**Comment by LilyAndres** [comment]
@matentzn I'm having this error when I'm trying to run the modules, by any chance you know what could be happening?

**Comment by matentzn** [comment]
The error (127) means, usually, that, that a file was not found. So my guess is, given 

```
dosdp-tools generate --table-format=csv --template=patterns/chemical_concentration.yaml --outfile=modules/chemical_concentration.tmp.owl --obo-prefixes=true --infile=templates/chemical_concentration.csv
```

That either:

- patterns/chemical_concentration.yaml or templates/chemical_concentration.csv does not exist or:
- the `modules` directory for modules/chemical_concentration.tmp.owl does not exist.

As an aside: pretty ancient ODK repo setup, could be updated

**Comment by kaiiam** [comment]
We think it's a docker issue as I was able to run it no problem on my computer, and lilly has also run it in the past. @LilyAndres perhaps you can just double check it by cloning the repo again and just running it to make sure it wasn't some silly file deletion issue on your branch?

> As an aside: pretty ancient ODK repo setup, could be updated

We created CDNO with ODK about 2 years ago, I guess that makes it ancient now :P

**Comment by LilyAndres** [comment]
@kaiiam I just cloned the repo and I still have the issue. However, I don't remember:

- modules/chemical_concentration.tmp.owl

we don't have this file. 

Question, should the concentration have these kind of permits:
<img width="663" alt="Screen Shot 2022-08-10 at 9 36 21 pm" src="https://user-images.githubusercontent.com/25215773/183891972-ad39f8ad-7b6f-412c-96b2-f1f0a8ff7985.png">

I think is not reading the chemical_concentration.owl

**Comment by matentzn** [comment]
Does the modules directory exist?

**Comment by LilyAndres** [comment]
@matentzn yes, modules directory exist
<img width="613" alt="Screen Shot 2022-08-10 at 9 55 38 pm" src="https://user-images.githubusercontent.com/25215773/183895076-0103aeec-2f8c-43a2-a051-8426c9fbd276.png">

**Comment by kaiiam** [comment]
Code works on my computer but not @LilyAndres I think this must be a docker issue or something like that. Can you update docker?

**Comment by matentzn** [comment]
I can recreate the issue: https://github.com/INCATools/dosdp-tools/issues/425

**Comment by LilyAndres** [comment]
@matentzn thanks a lot, I followed the changes you made in ENVO and it's working now :) I will close this issue now.

**Comment by kaiiam** [comment]
Excelent thank you very much @matentzn!
